package com.strumenta.funnellang

import com.strumenta.funnel.Person;
import com.strumenta.funnel.EmailScheduling;
import java.time.DayOfWeek;

dialect "java"
rule "Send book offer only after at least 3 book presentation emails"

   when
      person : Person (
          emailReceivedWithTag("book_explanation") < 3
      )
      scheduling : EmailScheduling(
        !blocked,
        sending.person = person,
        sending.email.tags contains "book_offer"
      )
   then
        scheduling.setBlocked(true);
end

dialect "java"
rule "Block book offers on monday"

   when
      scheduling : EmailScheduling(
        !blocked,
        sending.date.dayOfWeek = DayOfWeek.MONDAY
      )
   then
        scheduling.setBlocked(true);
end

dialect "java"
rule "Block book offers for people who bought"

   when
      person : Person (
          tags contains "book_bought"
      )
      scheduling : EmailScheduling(
        !blocked,
        sending.person = person,
        sending.email.tags contains "book_offer"
      )
   then
        scheduling.setBlocked(true);
end